<?php
namespace common\base;

/**
 * Created by PhpStorm.
 * User: Wbin
 * Date: 2018/1/21
 * Time: 20:02
 */
class User extends  \yii\web\User
{
    /**
     * @var string the session variable name used to store the value of [[id]].
     */
    public $idParam = '__backendId';

    public function __get($name)
    {
        if(null !== $this->getIdentity() && in_array($name, array_keys($this->getIdentity()->attributes))) {
            return $this->identity->$name;
        }
        return parent::__get($name); // TODO: Change the autogenerated stub
    }
}