<?php
namespace common\models;

use Yii;

/**
 * This is the model class for table "admin_parallel_volunteer".
 *
 * @property string $id
 * @property double $max_diff_score
 * @property double $min_diff_score
 * @property string $create_time
 * @property string $update_time
 * @property string $update_user
 */
class AdminParallelVolunteer extends \backend\models\BaseModel
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'admin_parallel_volunteer';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['max_diff_score', 'min_diff_score', 'volunteer_id'], 'required'],
            [['volunteer_id'], 'unique', 'message' => '已添加当前档次'],
            [['max_diff_score', 'min_diff_score'], 'number'],
            [['create_time', 'update_time', 'volunteer_id'], 'integer'],
            [['update_user'], 'string', 'max' => 128]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'volunteer_id' => '档次',
            'max_diff_score' => '最大分差',
            'min_diff_score' => '最小分差',
            'create_time' => '创建时间',
            'update_time' => '修改时间',
            'update_user' => '修改人',
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->max_diff_score < $this->min_diff_score) {
            $tmp = $this->max_diff_score;
            $this->max_diff_score = $this->min_diff_score;
            $this->min_diff_score = $tmp;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
