<?php
namespace common\models;

use backend\models\AdminMember;
use Yii;

/**
 * This is the model class for table "admin_finance_record".
 *
 * @property string $id
 * @property string $amount
 * @property integer $operate_type
 * @property string $remark
 * @property string $operate_name
 * @property string $create_time
 * @property string $ip
 */
class AdminFinanceRecord extends \backend\models\BaseModel
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'admin_finance_record';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['amount', 'member_id'], 'required'],
            [['amount'], 'number'],
            [['operate_type', 'create_time', 'member_id'], 'integer'],
            [['operate_type'], 'in', 'range' => [0, 1]],
            [['remark'], 'string', 'max' => 512],
            [['operate_name'], 'string', 'max' => 128],
            [['ip'], 'string', 'max' => 15]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'member_id' => '会员名',
            'amount' => '金额',
            'operate_type' => '操作类型',
            'remark' => '备注',
            'operate_name' => '操作人',
            'create_time' => '操作时间',
            'ip' => '操作人IP',
        ];
    }

    /**
     *
     */
    public function  afterSave($insert, $changedAttributes)
    {
        if ($insert) {
            $member = AdminMember::findOne(['id' => $this->member_id]);
            $member->wallet_balance = $this->operate_type
                ? bcsub($member->wallet_balance, $this->amount, 2) : bcadd($member->wallet_balance, $this->amount, 2);
            $member->save(false);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
